version: '3'

services:
  nginx:
    image: library/nginx:1.15.6-alpine
    ports:
    - '8000:80'
    depends_on:
    - app
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www/html

  app:
    build: ./docker/php
    volumes:
    - ./app:/var/www/html
