version: '3'

services:
  nginx:
    image: library/nginx:1.15.6-alpine
    ports:
    - '8000:80'
    depends_on:
    - app
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www/html

  app:
    build: ./docker/php
    volumes:
    - ./app:/var/www/html
    depends_on:
    - mysql

  mysql:
    image: mysql:5.7
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
    - MYSQL_DATABASE=twitter
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_USER=default
    - MYSQL_PASSWORD=password
    - TZ=Asia/Tokyo
    ports:
    - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
